# Edge System Deployment Configuration
# Progressive rollout with safety controls

system:
  name: "improved_edge_system"
  version: "2.0.0"
  risk_reward_ratio: 4.0  # 4:1 R:R

# Validation gates (must pass before deployment)
validation_gates:
  min_expectancy: 0.0025      # 0.25% per trade
  min_profit_factor: 1.30     # 30% edge
  min_trades: 100             # Statistical significance
  max_drawdown: 0.05          # 5% max DD
  min_sharpe: 1.0             # Risk-adjusted returns

# Shadow trading requirements
shadow_trading:
  enabled: true
  min_trades: 200             # Before going live
  max_halt_triggers: 1        # Max daily loss halts allowed
  max_latency_p95: 300        # ms
  metrics_endpoint: "http://localhost:9090/metrics"

# Progressive deployment schedule
deployment_phases:
  phase_1:
    name: "Verification"
    duration_days: 2
    risk_per_trade: 0.0025    # 0.25% of equity
    daily_loss_limit: 0.005   # 0.5% (2R)
    features:
      - basic_execution
      - latency_monitoring
      - slippage_tracking
  
  phase_2:
    name: "Confidence Building"
    duration_days: 2
    risk_per_trade: 0.005     # 0.5% of equity
    daily_loss_limit: 0.01    # 1% (2R)
    features:
      - smart_pyramiding
      - online_learning
      - multi_coin_rotation
  
  phase_3:
    name: "Full Production"
    duration_days: null       # Ongoing
    risk_per_trade: 0.01      # 1% of equity
    daily_loss_limit: 0.03    # 3% (3R)
    features:
      - all_features
      - aggressive_scaling
      - full_universe

# Risk controls
risk_management:
  position_limits:
    max_positions: 3          # Concurrent positions
    max_exposure: 0.03        # 3% total exposure
    max_correlated: 2         # Max correlated assets
  
  circuit_breakers:
    daily_loss_halt: -3.0     # -3R stops trading for 24h
    consecutive_losses: 5     # Triggers review
    drawdown_halt: 0.06       # 6% drawdown pauses system
  
  execution_controls:
    max_slippage_bps: 50      # 0.5% of spread
    max_latency_ms: 300       # Cancel if over
    min_liquidity: 100000     # Min 24h volume USD

# Monitoring and alerts
monitoring:
  prometheus:
    enabled: true
    port: 9090
    scrape_interval: 15s
  
  grafana:
    enabled: true
    port: 3000
    dashboards:
      - edge_performance
      - risk_metrics
      - execution_quality
  
  alerts:
    channels:
      - name: "bot-ops"
        type: "slack"
        webhook: "${SLACK_WEBHOOK_URL}"
    
    rules:
      - name: "hit_rate_deviation"
        condition: "abs(actual_hit_rate - expected_hit_rate) > 0.15"
        severity: "warning"
      
      - name: "profit_factor_degradation"
        condition: "rolling_pf_30 < 1.1"
        severity: "critical"
      
      - name: "drawdown_breach"
        condition: "current_dd > 0.06"
        severity: "critical"
      
      - name: "latency_spike"
        condition: "ws_latency_p95 > 300"
        count: 3
        window: "5m"
        severity: "warning"

# Online learning configuration
online_learning:
  enabled: true
  trigger_condition: "rolling_sharpe_100 < 0"
  max_epochs: 1
  learning_rate: 0.001
  revert_on_failure: true
  validation_split: 0.2

# Feature flags
features:
  USE_SMART_PYRAMID: true
  USE_MULTI_COIN: true
  USE_ONLINE_LEARNING: true
  USE_ATR_STOPS: true
  RISK_REWARD_RATIO: 4.0

# MLflow configuration
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "edge_system_v2"
  tags:
    r_r: "4:1"
    stop_type: "ATR"
    ensemble: "weighted"

# Logging
logging:
  level: "INFO"
  handlers:
    - type: "file"
      filename: "logs/edge_system.log"
      max_bytes: 10485760     # 10MB
      backup_count: 5
    - type: "console"
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Database
database:
  trades_db: "data/trades.db"
  metrics_db: "data/metrics.db"
  backup_interval: "1h"

# API endpoints
api:
  rest:
    enabled: true
    port: 8080
    endpoints:
      - "/health"
      - "/metrics"
      - "/positions"
      - "/performance"
  
  websocket:
    enabled: true
    port: 8081
    heartbeat: 30 